# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 03:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20170831_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='auhtors',
            new_name='authors',
        ),
    ]
